ficuni/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

from .views import (CycleCourseList, DepartmentElectiveList, CourseDetail,
                    DepartmentList, DepartmentDetail, TeacherDetail,
                    NewsletterDetail, CourseViewSet, TeacherViewSet,
                    LocationViewSet, IndexView, AnnouncementDetail)


app_name = 'ficuni'

router = DefaultRouter()
router.register('teachers', TeacherViewSet)
router.register('courses', CourseViewSet)
router.register('locations', LocationViewSet, 'Location')


urlpatterns = [
    path('api/', include((router.urls, 'api'), 'instance_name')),
    path('', IndexView.as_view(), name='index'),
    path('courses/ciclo-<int:cycle>/', CycleCourseList.as_view(),
         name='course_by_cycle'),
    path('courses/electivos/', DepartmentElectiveList.as_view(),
         name='electives_by_department'),
    path('course/<slug:code>/', CourseDetail.as_view(),
         name='course_detail'),
    path(_('departments/'), DepartmentList.as_view(),
         name='department_list'),
    path(_('department/<slug:acronym>/'), DepartmentDetail.as_view(),
         name='department_detail'),
    path('teacher/<int:pk>/', TeacherDetail.as_view(),
         name='teacher_detail'),
    path('cruce-de-horarios/',
         TemplateView.as_view(template_name="ficuni/cruce_horarios.html"),
         name='cruce_horarios'),
    path('deanery/',
         TemplateView.as_view(template_name="ficuni/deanery.html"),
         name='deanery'),
    url(r'^compartir-horario/.*',
        TemplateView.as_view(template_name="ficuni/share_schedule.html"),
        name='share_schedule'),
    path('newsletter/<slug:newsletter_type>/<slug:code>/',
         NewsletterDetail.as_view(),
         name='newsletter_detail'),
    path('announcement/<slug:code>/',
         AnnouncementDetail.as_view(),
         name='announcement_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ficunipage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    # path('', include('flatpages_i18n.urls')),
    path('admin/', admin.site.urls),
)

urlpatterns += [
    path('', include('ficuni.urls')),
]


urlpatterns += [
    path('summernote/', include('django_summernote.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ficuni/models.py
from PIL import Image as Img
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from io import BytesIO
import sys

from .storages import OverwriteStorage


class Classroom(models.Model):
    code = models.SlugField(_('code'), max_length=14, unique=True)

    def __str__(self):
        return str(self.code)

    class Meta:
        verbose_name = _('classroom')
        verbose_name_plural = _('classrooms')


class EvaluationSystem(models.Model):
    code = models.SlugField(_('code'), max_length=6, unique=True)

    def __str__(self):
        return str(self.code)

    class Meta:
        verbose_name = _('evaluation system')
        verbose_name_plural = _('evaluation systems')
        ordering = ('code',)


class Department(models.Model):
    acronym = models.SlugField(_('code'), max_length=14, unique=True)
    name = models.CharField(_('name'), max_length=126)
    summary = models.TextField(_('summary'), max_length=200, blank=True,
                               default='')
    organization = models.TextField(_('organization'), blank=True, default='')

    def __str__(self):
        return str(self.acronym)

    class Meta:
        verbose_name = _('department')
        verbose_name_plural = _('departments')


class Cycle(models.Model):
    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = _('cycle')
        verbose_name_plural = _('cycles')


class Course(models.Model):
    code = models.SlugField(_('code'), max_length=14, unique=True)
    name = models.CharField(_('name'), max_length=126)
    num_of_credits = models.PositiveSmallIntegerField(
        _('num. of credits'),
        validators=(
            MinValueValidator(1),
            MaxValueValidator(6),
        ))
    cycle = models.ForeignKey(
        Cycle, on_delete=models.SET_NULL, null=True,
        verbose_name=_('cycle')
    )
    evaluation_system = models.ForeignKey(
        EvaluationSystem, on_delete=models.SET_NULL, null=True,
        verbose_name=_('evaluation system')
    )
    department = models.ForeignKey(
        Department, on_delete=models.SET_NULL, null=True,
        verbose_name=_('department')
    )

    def __str__(self):
        return '{self.code}: {self.name}'.format(self=self)

    class Meta:
        verbose_name = _('course')
        verbose_name_plural = _('courses')
        ordering = ('code',)


class Section(models.Model):
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE,
        verbose_name=_('course')
    )
    section = models.CharField(_('section'), max_length=6)

    def __str__(self):
        return '{self.course.code}-{self.section}'.format(self=self)

    class Meta:
        verbose_name = _('section')
        verbose_name_plural = _('sections')
        ordering = ('course',)
        unique_together = (('section', 'course'),)


class Grade(models.Model):
    abbreviation = models.SlugField(_('abbreviation'), max_length=14,
                                    unique=True)

    def __str__(self):
        return str(self.abbreviation)

    class Meta:
        verbose_name = _('grade')
        verbose_name_plural = _('grades')


class Category(models.Model):
    name = models.CharField(_('name'), max_length=30)
    abbreviation = models.SlugField(_('abbreviation'), max_length=14, unique=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')


class Condition(models.Model):
    name = models.CharField(_('name'), max_length=30)
    abbreviation = models.SlugField(_('abbreviation'), max_length=14, unique=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = _('condition')
        verbose_name_plural = _('conditions')


class Dedication(models.Model):
    name = models.CharField(_('name'), max_length=62)
    abbreviation = models.SlugField(_('abbreviation'), max_length=14, unique=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = _('dedication')
        verbose_name_plural = _('dedications')


def teacher_photo_path(teacher, filename):
    return 'teacher/{}.{}'.format(teacher.code, 'jpg')


class Teacher(models.Model):
    code = models.SlugField(_('code'), max_length=14, unique=True, blank=True,
                            null=True)
    last_name = models.CharField(_('last name'), max_length=126)
    first_name = models.CharField(_('first name'), max_length=126)
    phone = models.CharField(_('phone'), max_length=62, blank=True, null=True)
    email = models.CharField(_('email'), max_length=126, blank=True, null=True)
    summary = models.TextField(_('summary'), max_length=200, blank=True,
                               null=True)
    birthday = models.DateField(_('birthday'), blank=True, null=True)
    photo = models.ImageField(_('photo'), upload_to=teacher_photo_path,
                              storage=OverwriteStorage(), blank=True, null=True)
    grade = models.ForeignKey(
        Grade, on_delete=models.SET_NULL, null=True,
        verbose_name=_('grade')
    )
    departments = models.ManyToManyField(
        Department,
        verbose_name=_('departments')
    )
    dedication = models.ForeignKey(
        Dedication, on_delete=models.SET_NULL, blank=True, null=True,
        verbose_name=_('dedication')
    )
    condition = models.ForeignKey(
        Condition, on_delete=models.SET_NULL, blank=True, null=True,
        verbose_name=_('condition')
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, blank=True, null=True,
        verbose_name=_('category')
    )

    def __str__(self):
        return '{self.last_name}, {self.first_name}'.format(self=self)

    def save(self, *args, **kwargs):
        if self.photo:
            image = Img.open(BytesIO(self.photo.read()))
            output = BytesIO()
            image_resized = image.resize((210, 280))
            image_resized.save(output, format='JPEG', quality=75)
            output.seek(0)
            self.photo = InMemoryUploadedFile(output, 'ImageField',
                                              '{}.jpg'.format(self.code),
                                              'image/jpeg',
                                              sys.getsizeof(output), None)
        super(Teacher, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _('teacher')
        verbose_name_plural = _('teachers')
        ordering = ('last_name', 'first_name',)


class HourType(models.Model):
    abbreviation = models.SlugField(_('abbreviation'), max_length=8,
                                    unique=True)
    name = models.CharField(_('name'), max_length=14)

    def __str__(self):
        return str(self.abbreviation)

    class Meta:
        verbose_name = _('hour type')
        verbose_name_plural = _('hour types')


class Location(models.Model):
    days_of_week = (
        (1, _('monday')),
        (2, _('tuesday')),
        (3, _('wednesday')),
        (4, _('thursday')),
        (5, _('friday')),
        (6, _('saturday')),
    )
    week_day = models.PositiveSmallIntegerField(_('day of week'),
                                                choices=days_of_week)
    begin_hour = models.PositiveSmallIntegerField(
        _('begin hour'),
        validators=(
            MinValueValidator(8),
            MaxValueValidator(21),
        ))
    end_hour = models.PositiveSmallIntegerField(
        _('end hour'),
        validators=(
            MinValueValidator(8),
            MaxValueValidator(21),
        ))
    hour_type = models.ForeignKey(
        HourType, on_delete=models.SET_NULL, null=True,
        verbose_name=_('hour type')
    )
    classrooms = models.ManyToManyField(
        Classroom,
        verbose_name=_('classrooms')
    )
    teachers = models.ManyToManyField(
        Teacher,
        verbose_name=_('teachers'),
        #limit_choices_to={'departments__acronym': 'DACB'}
    )
    section = models.ForeignKey(Section, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('location')
        verbose_name_plural = _('locations')
        unique_together = (
            ('week_day', 'begin_hour', 'end_hour', 'hour_type', 'section'),
        )


class NewsletterType(models.Model):
    name = models.CharField(max_length=62)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = _('newsletter type')
        verbose_name_plural = _('newsletter types')


class Newsletter(models.Model):
    code = models.SlugField(_('code'), max_length=14, unique=True)
    title = models.CharField(_('title'), max_length=126)
    pub_date = models.DateField(_('date published'))
    newsletter_type = models.ForeignKey(NewsletterType,
                                        on_delete=models.SET_NULL, null=True)
    file = models.FileField(upload_to='newsletters')

    class Meta:
        verbose_name = _('newsletter')
        verbose_name_plural = _('newsletters')


class Announcement(models.Model):
    code = models.SlugField(_('code'), max_length=14, unique=True)
    title = models.CharField(_('title'), max_length=126)
    pub_date = models.DateField(_('date published'))
    file = models.FileField(upload_to='announcements')

    class Meta:
        verbose_name = _('announcement')
        verbose_name_plural = _('announcements')

ficuni/templates/ficuni/announcement_detail.html
{% extends 'ficuni/base.html' %}
{% load l10n %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Announcement" %} {{ announcement.code }}{% endblock %}

{% block container %}
<h2>
  {% trans "Announcement" %} {{ announcement.code }}
  <small class="text-muted">{{ announcement.title }}</small>
</h2>
<div class="row">
  <div class="col-lg-8">
    <object class="img-fluid" data="{% get_media_prefix %}{{ announcement.file }}", style="width: 100%; height: calc(100vh - 126.4px);">
      <a href="{% get_media_prefix %}{{ announcement.file }}">{{ announcement.code }}.pdf</a>
    </object>
  </div>
  <div class="col-lg-4">
    <ul>
    {% for month, l in announcement_list %}
      <li>{{ month|date:"F Y" }}
        <ul>
          {% for a in l %}
          <li><a href="{% url 'ficuni:announcement_detail' a.code %}">{% trans "Announcement" %} {{ a.code }}<br/>({{ a.pub_date}})</a></li>
          {% endfor %}
        </ul>
      </li>
    {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

ficuni/templates/ficuni/base.html
{#{% load static i18n flatpages_i18n %}#}
{% load static i18n %}
{% get_available_languages as LANGUAGES %}
{% get_current_language as LANGUAGE_CODE %}
{% load render_bundle from webpack_loader %}
{% load analytical %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    {% analytical_head_top %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Facultad de Ingeniería Civil - UNI{% endblock %}</title>
    {% block stylesheets %}
    {% render_bundle 'base' 'css' %}
    {% endblock %}
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}" />
    {% analytical_head_bottom %}
  </head>
  <body>
    {% analytical_body_top %}
    {% block navbar %}
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark">
      <a class="navbar-brand" href="{% url 'ficuni:index' %}">
        <img class="d-inline-block align-top" src="{% static 'ficuni/images/UNI_logo.svg' %}" height="30" alt="Logo UNI">
        FIC-UNI
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% trans "About the career" %}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% comment %}
              {% get_flatpage_i18n 'mission_vision' as mission_vision_flatpage %}
              <a class="dropdown-item" href="/{{ LANGUAGE_CODE }}{{ mission_vision_flatpage.url }}">
                {{ mission_vision_flatpage.title }}
              </a>
              {% get_flatpage_i18n 'dean' as dean_flatpage %}
              <a class="dropdown-item" href="/{{ LANGUAGE_CODE }}{{ dean_flatpage.url }}">
                {{ dean_flatpage.title }}
              </a>
              <div class="dropdown-divider"></div>
              {% get_flatpage_i18n 'entrant_profile' as entrant_profile_flatpage %}
               <a class="dropdown-item" href="/{{ LANGUAGE_CODE }}{{ entrant_profile_flatpage.url }}">
                {{ entrant_profile_flatpage.title }}
              </a>
              {% get_flatpage_i18n 'graduate_profile' as graduate_profile_flatpage %}
              <a class="dropdown-item" href="/{{ LANGUAGE_CODE }}{{ graduate_profile_flatpage.url }}">
                {{ graduate_profile_flatpage.title }}
              </a>
              <div class="dropdown-divider"></div>
              {% endcomment %}
              <a class="dropdown-item" href="{% url 'ficuni:deanery' %}">
                {% trans "Dean" %}
              </a>
              <a class="dropdown-item" href="{% url 'ficuni:department_list' %}">
                {% trans "Departments" %}
              </a>
              <a class="dropdown-item" href="{% url 'ficuni:electives_by_department' %}">
                {% trans "Courses" %}
              </a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% trans "Information for students" %}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'ficuni:cruce_horarios' %}">Cruce de horarios</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% trans "Institutes, centres and laboratories" %}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" data-toggle="tooltip" title="Instituto de Investigación de la FIC" target="_blank" href="http://www.iific.uni.edu.pe">IIFIC</a>
              <a class="dropdown-item" data-toggle="tooltip" title="Instituto para la Mitigación de los Efectos del Fenómono El Niño" target="_blank" href="http://www.imefen.uni.edu.pe">IMEFEM</a>
              <a class="dropdown-item" data-toggle="tooltip" title="Centro de Cómputo de la FIC" target="_blank" href="http://ccfic.uni.edu.pe">CC-FIC</a>
              <a class="dropdown-item" data-toggle="tooltip" title="Centro Peruano Japonés de Investigaciones Sísmicas y Mitigación de Desastres" target="_blank" href="http://www.cismid.uni.edu.pe">CISMID</a>
              <a class="dropdown-item" data-toggle="tooltip" title="Centro de Educación Continua FIC" target="_blank" href="http://cecfic.uni.edu.pe">CEC-FIC</a>
              <a class="dropdown-item" data-toggle="tooltip" title="Acreditación FIC" target="_blank" href="http://www.acreditacionfic.uni.edu.pe">Acreditación FIC</a>
              <a class="dropdown-item" data-toggle="tooltip" title="Postgrado FIC" target="_blank" href="http://www.postgradofic.uni.edu.pe/">Postgrado FIC</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" target="_blank" href="http://www.labdcv.uni.edu.pe">Lab. de Diseño y Construcción Virtual</a>
              <a class="dropdown-item" target="_blank" href="http://www.lem.uni.edu.pe">Lab. de Ensayo de Materiales</a>
              <a class="dropdown-item" target="_blank" href="http://www.lms.uni.edu.pe">Lab. de Mecánica de Suelos</a>
              <!--<a class="dropdown-item disabled" href="#">Lab. Nacional de Hidráulica</a>-->
              <!--<a class="dropdown-item disabled" href="#">Lab. de Física</a>-->
              <a class="dropdown-item" target="_blank" href="http://www.labquimica.uni.edu.pe">Lab. de Química</a>
              <!--<div class="dropdown-divider"></div>-->
              <!--<a class="dropdown-item disabled" href="#">Biblioteca «Alberto Regal»</a>-->
            </div>
          </li>
        </ul>
      </div>
    </nav>
    {% endblock %}

    {% block body %}
    <div class="container py-4 px-sm-5">
      {% block container %}
      {% endblock %}
    </div>
    {% endblock %}

    {% block footer %}
    <footer class="pt-5 text-light">
      <div class="container">
          <div class="row">
            <div class="col-sm-6 col-lg-3 pb-4 text-center">
              <a target="_blank" href="http://www.uni.edu.pe">
                <img src="{% static 'ficuni/images/UNI_logo3.svg' %}" alt="Logo UNI" height="67">
              </a>
            </div>
            <div class="col-sm-6 col-lg-3 pb-4 text-center">
              <a target="_blank" href="http://www.abet.org">
                <img src="{% static 'ficuni/images/ABET_logo.svg' %}" alt="Logo ABET" height="67">
              </a>
            </div>
            <div class="col-sm-6 col-lg-3 pb-4">
              <h5>{% trans "Academics" %}</h5>
              <ul class="list-unstyled text-small">
                <li><a class="text-light" href="{% url 'ficuni:electives_by_department' %}">{% trans "Courses" %}</a></li>
                <li><a class="text-light" href="{% url 'ficuni:department_list' %}">{% trans "Departments" %}</a></li>
              </ul>
            </div>
            <div class="col-sm-6 col-lg-3 pb-4">
              <h5>{% trans "Language" %}</h5>
              <form class="form-inline" action="{% url 'set_language' %}" method="post">{% csrf_token %}
                  <input name="next" type="hidden" value="{% url 'ficuni:index' %}">
                <select name="language" class="form-control form-control-sm">
                  {% get_current_language as LANGUAGE_CODE %}
                  {% get_available_languages as LANGUAGES %}
                  {% get_language_info_list for LANGUAGES as languages %}
                  {% for language in languages %}
                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                      {{ language.name_local }} ({{ language.code }})
                    </option>
                  {% endfor %}
                </select>
                <button type="submit" class="btn btn-dark btn-sm" value="Go">Go</button>
              </form>
            </div>
          </div>
      </div>
    </footer>
    {% endblock %}

    {% block javascripts %}
      {% render_bundle 'base' 'js' %}
    {% endblock %}
    {% analytical_body_bottom %}
  </body>
</html>

ficuni/templates/ficuni/course_list.html
{% extends 'ficuni/base.html' %}

{% block container %}
<div class="row">
  <div class="col-md-3">
    <h4>Ciclo</h4>
    <ul class="nav nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      {% for cycle in cycle_list %}
      <li class="{% if cycle.id < 11 %}w-50{% else %}w-100{% endif %}">
        {# TODO: Use ARIA #}
        <a class="nav-link text-center {% if cycle.id == current_cycle.id %}active{% endif %}"
          href="{% url "ficuni:course_by_cycle" cycle.id %}">
          {% if cycle.id < 11 %}
            Ciclo {{ cycle.id }}
          {% else %}
            Electivos
          {% endif %}
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>
  <div class="col-md-9">
    {% block course_list %}
    {% endblock %}
  </div>
</div>
{% endblock %}

ficuni/templates/ficuni/courses_by_cycle.html
{% extends 'ficuni/course_list.html' %}

{% block title %}
    {% if current_cycle.id < 11 %}
      Ciclo {{ current_cycle.id }}
    {% else %}
      Electivos
    {% endif %}
{% endblock %}

{% block course_list %}
    <h3>
      {% if current_cycle.id < 11 %}
        Ciclo {{ current_cycle.id }}
      {% else %}
        Electivos
      {% endif %}
    </h3>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Código</th>
          <th scope="col">Curso</th>
          <th scope="col">Créd.</th>
          <th scope="col">Dept.</th>
        </tr>
      </thead>
      <tbody>
        {% for course in course_list %}
        <tr>
          <th scope="row">
            <a href="{% url 'ficuni:course_detail' course.code %}">{{ course.code }}</a>
          </th>
          <td>
            <a href="{% url 'ficuni:course_detail' course.code %}">
                {{ course.name }}
            </a>
           </td>
          <td>
            {{ course.num_of_credits }}
          </td>
          <td>
            <a href="{% url 'ficuni:department_detail' course.department.id %}">{{ course.department.acronym }}</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}

ficuni/templates/ficuni/department_detail.html
{% extends 'ficuni/base.html' %}

{% block title %}
  {{ department.acronym }} - Dept. Acad. de {{ department.name }}
{% endblock %}

{% block container %}
<ul class="nav nav-tabs justify-content-end">
  {% for dept in department_list %}
  <li class="nav-item">
    {# TODO: Use ARIA #}
    <a class="nav-link text-center {% if department.id == dept.id %}active{% endif %}"
      href="{% url "ficuni:department_detail" dept.acronym %}">
      {{ dept.acronym }}
    </a>
  </li>
  {% endfor %}
</ul>
<h2 class="pt-3">
  Departamento Académico de {{ department.name }}
  <p class="lead">{{ department.code }}</lead>
</h2>
<div class="row">
  <div class="col-lg-5">
    {% comment %}
    // It'd be nice if there were summaries :c
    <h3>Reseña</h3>
    <div class="text-justify">
      {{ department.summary }}
    </div>
    {% endcomment %}
    <h3>Organización</h3>
    <div class="">
      {{ department.organization|safe }}
    </div>

  </div>
  <div class="col-lg-7">
    <h3>Cursos</h3>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Código</th>
          <th scope="col">Curso</th>
          <th scope="col">Créditos</th>
          <th scope="col">Ciclo</th>
        </tr>
      </thead>
      <tbody>
        {% for course in department.course_set.all %}
        <tr>
          <th scope="row"><a href="{% url 'ficuni:course_detail' course.code %}">{{ course.code }}</a></th>
          <td><a href="{% url 'ficuni:course_detail' course.code %}">
              {{ course.name }}
          </a></td>
          <td>{{ course.num_of_credits }}</td>
          <td>{{ course.cycle.id }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <h3>Profesores</h3>
    <table class="table">
      <thead>
        <th scope="col">Código</th>
        <th scope="col">Docente</th>
        <th scope="col">Categoría</th>
      </thead>
      <tbody>
        {% for teacher in department.teacher_set.all %}
        <tr>
          <th scope="row">
            <a href="{% url 'ficuni:teacher_detail' teacher.id %}">{{ teacher.code }}</a>
          </th>
          <td>
            <a href="{% url 'ficuni:teacher_detail' teacher.id %}">{{ teacher.grade}} {{ teacher.last_name }}, {{ teacher.first_name }}</a>
          </td>
          <td>
            {{ teacher.category.name }}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

ficuni/templates/ficuni/department_list.html
{% extends 'ficuni/base.html' %}

{% block container %}
<div class="row">
{% for department in department_list %}
  <div class="col-sm-6">
    <div class="card my-2">
      <div class="card-body">
        <h5 class="card-title">{{ department.acronym }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">Dept. Acad. de {{ department.name }}</h6>
        <div class="card-text text-justify">
          {{ department.summary }}
        </div>
        <a href="{% url 'ficuni:department_detail' department.acronym %}" class="card-link">Ver más</a>
      </div>
    </div>
  </div>
{% endfor %}
</div>
{% endblock %}

ficuni/templates/ficuni/electives_by_department.html
{% extends 'ficuni/course_list.html' %}

{% block course_list %}
    <h3>Electivos</h3>
    {% for department in department_list %}
    <h4>Departamento Académico de {{ department.name }}</h4>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Código</th>
          <th scope="col">Curso</th>
          <th scope="col">Créd.</th>
        </tr>
      </thead>
      <tbody>
        {% for course in department.course_set.all %}
        {# TODO: NOT USE IF TO FILTER!, but it works #}
        {% if course.cycle.id == 11 %}
        <tr>
          <th scope="row">
            <a href="{% url 'ficuni:course_detail' course.code %}">
              {{ course.code }}
            </a>
          </th>
          <td>
            <a href="{% url 'ficuni:course_detail' course.code %}">
              {{ course.name }}
            </a>
           </td>
          <td>
            {{ course.num_of_credits }}
          </td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
    {% endfor %}
{% endblock %}